services:
  apache:
    build: ./
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: nein
      MYSQL_DATABASE: pokedex
      MYSQL_USER: alexfmks
      MYSQL_PASSWORD: lifehouse204
    ports:
      - "3307:3306"
    restart: always
#    adminer:
#      image: adminer
#      restart: always
#      ports:
#        - "8080:8080"

